"""add game_type to rooms

Revision ID: 257334174557
Revises: 7ecf0b299d96
Create Date: 2026-09-03 14:40:29.554614

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "257334174557"
down_revision: str | Sequence[str] | None = "7ecf0b299d96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("game_type", sa.String(length=16), server_default="taidi", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "game_type")
    # ### end Alembic commands ###
